import type { NextPage } from "next";
import Image from "next/image";
import Head from "next/head";
import ToggleSwitch from "../components/Switch";

const unsplashLoader = ({ width }: { width: number }) => {
  return `https://images.unsplash.com/flagged/photo-1570612861542-284f4c12e75f?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=${width}&q=80`;
};

const Home: NextPage = () => {
  return (
    <div className="flex flex-col h-full">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="flex flex-col flex-none px-8 py-4 h-24 bg-black">
        <h1 className="text-white font-bold text-3xl tracking-wide">
          React Conf
        </h1>
        <p className="text-white font-light">London</p>
      </header>

      <main className="h-screen">
        {/* Presenter & talk info */}
        <div className="flex flex-col mt-4 px-8 space-y-2">
          <h2 className="capitalize">presenter Name</h2>
          <div className="flex">
            <div className="h-28 w-28 relative flex-none">
              {" "}
              <Image
                loader={unsplashLoader}
                src="me.pn"
                alt="Picture of the author"
                layout="fill"
                objectFit="cover"
              />
            </div>
            <p className="ml-4">This will be the title of the talk</p>
          </div>
        </div>
        {/* The form */}
        <div className="mt-8">
          <form className="flex space-y-6">
            <fieldset className="flex flex-col space-y-4 px-8">
              <label className="font-bold" htmlFor="full-name-input">
                Full Name
              </label>
              <input
                type="text"
                name="full-name-input"
                className="h-12 w-72 border-2 border-black capitalize px-2"
                placeholder="Curious George"
              />
              <label className="font-bold" htmlFor="email-input">
                Email
              </label>
              <input
                type="text"
                name="email-input"
                className="h-12 w-72 border-2 border-black px-2"
                placeholder="me@curiousgeorge.com"
              />

              <label className="font-bold" htmlFor="email-input">
                Options
              </label>
              <div className="bg-gray-100 flex flex-col py-2 space-y-2">
                <div className="flex flex-row h-12 px-8 py-2">
                  <ToggleSwitch description="Get notified when the video of this talk is published" />
                </div>
                <hr />
                <div className="flex flex-row h-12 px-8 py-2">
                  <ToggleSwitch description="Help me improve by grading my performance" />
                </div>
              </div>
              <button
                type="submit"
                className="w-72 h-16 bg-black text-white font-bold text-xl align-middle"
              >
                Submit
              </button>
            </fieldset>
          </form>
        </div>
      </main>

      <footer className="flex flex-none justify-center p-2 h-10 bg-black text-white text-sm">
        <p>
          Powered by{" "}
          <a
            className="text-green-500"
            href="#"
            target="_blank"
            rel="noopener noreferrer"
          >
            Ngosi
          </a>
        </p>
      </footer>
    </div>
  );
};

export default Home;
